# Site settings
title: "JeffBio.com"
email: contact@jeffbio.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome! I am Jeffrey Bhasin, a scientist who employs molecular medicine, bioinformatics, and data science towards the improvement of human health
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffbio.com" # the base hostname & protocol for your site
github_username:  jeffbhasin

# Build settings
markdown: kramdown
exclude: [methylaction_howto,goldmine_howto]
